---

- name: Setup RPM specific variables (set_fact)
  set_fact:
    tor_user: toranon
    tor_ConfDir: /etc/tor
    tor_RunAsDaemon: 0
    tor_DataDir: /var/lib/tor-instances
  tags:
   - reconfigure
   - renewkey
   - createdir

- name: Ensure tor package is installed (dnf)
  become: yes
  dnf: name=tor,libselinux-python,libsemanage-python state=present
  when: ansible_pkg_mgr == 'dnf'
  notify: re-gather facts

# re-gathering facts after installing libselinux-python on F23
# is a workaround for https://github.com/ansible/ansible-modules-core/issues/2432
- meta: flush_handlers

- name: Ensure EPEL repo is installed (yum)
  become: yes
  yum: name=epel-release
  when: ansible_pkg_mgr == 'yum'

- name: Ensure tor package is installed (yum)
  become: yes
  yum: name=tor,libsemanage-python state=present
  when: ansible_pkg_mgr == 'yum'

- name: Ensure SELinux boolean (tor_can_network_relay) is set appropriately (Fedora)
  become: yes
  seboolean: name=tor_can_network_relay state=yes persistent=yes
  when: ansible_selinux.status == 'enabled'
